{% set name = "libtirpc" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/libtirpc/libtirpc-{{ version }}.tar.bz2
  sha256: 1e0b0c7231c5fa122e06c0609a76723664d068b0dba3b8219b63e6340b347860

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
  - test -f $PREFIX/lib/libtirpc$SHLIB_EXT
about:
  home: http://git.linux-nfs.org/?p=steved/libtirpc.git;a=summary
  summary: 'Libtirpc is a Transport-Independent RPC library for Linux'
  description: |
    The libtirpc package contains libraries that support programs that use the
    Remote Procedure Call (RPC) API. It replaces the RPC, but not the NIS library
    entries that used to be in glibc.
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING

extra:
  recipe-maintainers:
    - cphyc
