{% set name = "libtirpc" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/libtirpc/libtirpc-{{ version }}.tar.bz2
  sha256: bbd26a8f0df5690a62a47f6aa30f797f3ef8d02560d1bc449a83066b5a1d3508

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make

test:
  commands:
    - test -f $PREFIX/lib/libtirpc$SHLIB_EXT
about:
  home: http://git.linux-nfs.org/?p=steved/libtirpc.git;a=summary
  summary: 'Libtirpc is a Transport-Independent RPC library for Linux'
  description: |
    The libtirpc package contains libraries that support programs that use the
    Remote Procedure Call (RPC) API. It replaces the RPC, but not the NIS library
    entries that used to be in glibc.
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING

extra:
  recipe-maintainers:
    - cphyc
